name: spinmouse
dependencies:
  - python=3.8
  - pip=22.1.2
  - pip:
    - opencv-python==4.6.0.66
    - numpy==1.23.3
    - matplotlib==3.6.0
    - pillow==9.2.0
    - keyboard==0.13.5
    - pyinstaller==5.6.2
    - tomlkit==0.11.6
